
namespace AgileSouthwestCMSAPI.Application.DTOs.Orders;

public record CreateOrderResult(
    int Id,
    string OrderNumber,
    string CustomerEmail,
    string CustomerFirstName,
    string CustomerLastName,
    string CustomerPhone,
    string Status,
    string PaymentStatus,
    string FulfillmentStatus,
    int SubtotalCents,
    int ShippingCents,
    int TaxCents,
    int TotalCents,
    int DiscountCents,
    string CouponCode,
    int CouponDiscountCents,
    int RefundedAmountCents,
    int PaymentServiceFeeCents,
    string Currency,
    string ShippingAddressLine1,
    string ShippingAddressLine2,
    string ShippingCity,
    string ShippingState,
    string ShippingPostalCode,
    string ShippingCountry,
    string BillingAddressLine1,
    string BillingAddressLine2,
    string BillingCity,
    string BillingState,
    string BillingPostalCode,
    string BillingCountry,
    string OrderType,
    string IpAddress,
    string UserAgent,
    string CustomerNotes,
    string AdminNotes,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    DateTime? DeletedAt,
    DateTime RowVersion
);